[theme]
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"

[server]
maxUploadSize = 5
enableCORS = false
enableXsrfProtection = false
gatherUsageStats = false

[global]
mainFile = "streamlit_app_lite.py" 